version: '3.4'

services:
  shopnetcoreapi:
    image: ${DOCKER_REGISTRY-}shopnetcoreapi
    build:
      context: .
      dockerfile: ShopNetCoreApi/Dockerfile
    ports:
      - "9080:80"
    depends_on:
      - migrations
      - db  
    networks:
      - your-network
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Bcdai@321996"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    depends_on: 
      - migrations
    networks:
      - your-network
  migrations:
    build: 
      context: .
      dockerfile: ShopNetCoreApi/Migrations.Dockerfile
    networks:
      - your-network
networks:
  your-network:
        name: your-network
