version: '3.4'

services:
  shopnetcoreapi:
    image: ${DOCKER_REGISTRY-}shopnetcoreapi
    build:
      context: .
      dockerfile: ShopNetCoreApi/Dockerfile
    ports:
      - "9080:80"
    depends_on:
      - db  
    networks:
      - your-network
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Bcdai@321996"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    networks:
      - your-network
    volumes:
       - /var/lib/sql/data
    restart: always
   
networks:
  your-network:
        name: your-network



   